define(['ojs/ojcore'], function (oj) {
    var ComorbLookup =
            [
                {"komid": 51, "label": "Adipositas"},
                {"komid": 42, "label": "Anämie, makrozytär"},
                {"komid": 52, "label": "Augenerkrankungen"},
                {"komid": 3, "label": "Diabetes mellitus"},
                {"komid": 10, "label": "Magen-/Darmerkrankungen, andere chronische"},
                {"komid": 11, "label": "Neoplasie, maligne"},
                {"komid": 14, "label": "Psoriasis"},
                {"komid": 47, "label": "Sjögren Syndrom"},
                {"komid": 18, "label": "Sonstige Erkrankung"},
                {"komid": 0, "label": "keine weitere chronische Erkrankung"},
                {"komid": 40, "label": "Anämie, normozytär"},
                {"komid": 41, "label": "Anämie, mikrozytär"},
                {"komid": 1, "label": "Atemwegs-/Lungenerkrankung, chronisch"},
                {"komid": 2, "label": "Depression/psychische Erkrankung"},
                {"komid": 23, "label": "Fettstoffwechselstörung"},
                {"komid": 37, "label": "chronisches Schmerzsyndrom/Fibromyalgie"},
                {"komid": 36, "label": "Gallenwegserkrankung"},
                {"komid": 4, "label": "Gastritis-/Ulkusanamnese"},
                {"komid": 5, "label": "Gelenkerkrankung, degenerative"},
                {"komid": 24, "label": "Hauterkrankung"},
                {"komid": 6, "label": "Herzerkrankung, koronare/andere"},
                {"komid": 7, "label": "Hypercholesterinämie / Fettstoffwechselstörung"},
                {"komid": 8, "label": "Hypertonie, arterielle"},
                {"komid": 9, "label": "Lebererkrankung, chronisch"},
                {"komid": 32, "label": "Lungenerkrankung"},
                {"komid": 21, "label": "Lymphom"},
                {"komid": 26, "label": "Migräne"},
                {"komid": 50, "label": "Neoplasie, ausschließlich Lymphom"},
                {"komid": 12, "label": "Nierenerkrankung, chronisch"},
                {"komid": 13, "label": "Osteoporose"},
                {"komid": 43, "label": "Osteoporose, manifest mit Fraktur"},
                {"komid": 27, "label": "Osteopenie"},
                {"komid": 45, "label": "Rheumaknoten"},
                {"komid": 22, "label": "Schilddrüsenerkrankung"},
                {"komid": 15, "label": "Schlaganfall / Durchblutungsstörung des Gehirns"},
                {"komid": 25, "label": "Tumorerkrankung"},
                {"komid": 16, "label": "Verschlusskrankheit, periphere arterielle"},
                {"komid": 17, "label": "Wirbelsäulenerkrankung, degenerative/Bandscheibenvorfall"},
                {"komid": 53, "label": "Perniziöse Anaemie mit Nachweis von Parietalzell-AK, Autoimmunthyreoiditis"},
                {"komid": 55, "label": "Gefäßerkrankungen"},
                {"komid": 57, "label": "Vorhofflimmern"}
            ];
    return ComorbLookup;
});
